# -*- coding: utf-8 -*-
"""klasifikasistadiumkankerparu .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I4c0u-RrNjr71czPD6nSleoeSppEwRc9
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.metrics import accuracy_score, classification_report

df = pd.read_csv('/content/drive/MyDrive/dtmn_6/lungc.csv', header=None)
df.columns = df.iloc[0]
df = df[1:]
df.reset_index(drop=True, inplace=True)

df = df.drop(columns='Patient Id')
df['Level'] = df['Level'].replace({'Low': 1, 'Medium': 2, 'High': 3})

print(df.head())

import matplotlib.pyplot as plt
import seaborn as sns
correlation_matrix = df.corr()
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Korelasi')
plt.show()

X = df[['Air Pollution','Alcohol use','Fatigue']]
y = df['Level'].values - 1

scaler = StandardScaler()
X = scaler.fit_transform(X)

svm_model = SVC()
xgb_model = XGBClassifier()
bagging_model = BaggingClassifier(estimator=SVC(), n_estimators=10, random_state=0)

kf = KFold(n_splits=5, shuffle=True, random_state=52)

svm_scores = cross_val_score(svm_model, X, y, cv=kf, scoring='accuracy')
xgb_scores = cross_val_score(xgb_model, X, y, cv=kf, scoring='accuracy')
bagging_scores = cross_val_score(bagging_model, X, y, cv=kf, scoring='accuracy')

print("SVM Accuracy: %0.2f (+/- %0.2f)" % (svm_scores.mean(), svm_scores.std() * 2))
print("XGBoost Accuracy: %0.2f (+/- %0.2f)" % (xgb_scores.mean(), xgb_scores.std() * 2))
print("Bagging Tree Accuracy: %0.2f (+/- %0.2f)" % (bagging_scores.mean(), bagging_scores.std() * 2))